### PR TITLE
Goreportcard badge

### PR DESCRIPTION
**Pull request by kevgo**

### CODE REVIEW

**Comment by charlierudolph** [comment]
Why do we need this? We have linters to enforce this (we can enable misspell as thats the only one displayed that we are not currently linting) aside from the license and thus should always be at 100%

**Comment by kevgo** [comment]
This gives us another nice green badge that tells other people looking at this repo in less than a second that this library has great code quality, and a team that cares about such things. That's a huge factor for me when evaluating other libraries.

**Comment by charlierudolph** [comment]
I think badges are more important for developers to know when things need to updated. Since we enforce it via linting, I don't think its needed. My bias is also from seeing repos with way to many badges and I'd rather have the minimal amount.

I also would debate that a repo with great code quality is automatically great. A repo can have great code quality (determined by some tool) and have a terrible APi or not do anything useful.

**Comment by charlierudolph** [comment]
To clarify 

> I also would debate that a repo with great code quality is automatically great. 

I think the API is far more important to look at first then the code quality

**Comment by kevgo** [comment]
All true statements, with which I don't disagree. Yet, in my opinion, badges are foremost for _users_ of the library. Developers have CI and command-line tools to get more detailed information as part of their development processes, rather than the binary red/green flag from badges. Developers also want to get them pushed to them, without having pull them by looking at the Github website in a browser. For example, our `publish` scripts indicate to developers if dependencies are out of date. That, plus alerts from dependency monitoring services like Gemnasium about important dependency updates are the right places to keep developers actively in the loop about these things imo.

Another important badge we should add is for test coverage. Similarly to the Goreportcard, seeing 90+% coverage doesn't _guarantee_ great testing nor code structure, but it _provides confidence_ that the developers are aware of testing and keep a tab on it. That's valuable.

I agree that ultimately looking through the source is the best way to assess the quality of a code base, yet that is also prohibitively expensive in most cases. So we need pragmatic compromise solutions that help promote our libraries by providing some amount of the value for a fraction of the cost. Badges are that. 

Just because some people abuse badges should not prevent us from using them correctly. The mistakes of less experienced people are not the guidelines through which I define my work. I look more to how experienced people do it right.

**Pull request merged**
